### Get all patients
GET http://localhost:3001/api/patients

### Add new patient
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "John Doe",
  "dateOfBirth": "1990-01-01",
  "ssn": "123456-789A",
  "gender": "male",
  "occupation": "tester"
}