### Get all patients
GET http://localhost:3001/api/patients

### Add new patient
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "John Doe",
  "dateOfBirth": "1990-01-01",
  "ssn": "123456-789A",
  "gender": "male",
  "occupation": "tester"
}

### Add new entry for a patient
POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "type": "HealthCheck",
  "description": "test entry",
  "date": "2024-01-01",
  "specialist": "Dr Test",
  "healthCheckRating": 1
}

### Add new entry - invalid rating (should fail with 400)
POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "type": "HealthCheck",
  "description": "test entry",
  "date": "2024-01-01",
  "specialist": "Dr Test",
  "healthCheckRating": 5
}